<div class="card">
    <div class="inset nomargin">
    
    <p>Hey! I'm AmazinAxel and I own this website and domain, AmazinAxel.com, along with other affiliated websites and domains (such as [AlecsHome.com](https://alecshome.com)).</p>
    <br>
    
    <h3>I care a lot about privacy and security. Please read this policy throughly [or the TL;DR at the bottom](#TLDR) so you understand your privacy whilst being on my site.</h3>
    </div>
    
    <br>
    <span>I have to comply with all security and safety standards, such as the <div class="tooltip">CCPA<span class="tooltiptext">The California Consumer Privacy Act is a law that requires me to disclose what data I collect about you and how I use it.</span></div> and the <div class="tooltip">GDPR<span class="tooltiptext">The General Data Protection Regulation is an EU law that requires me to give you options for how I use your data.</span></div>.</span>
    <span>I make sure not to put any <div class="tooltip">cookies<span class="tooltiptext">A cookie (not the type you eat) is a small amount of information stored in your browser for saving information such as passwords and tracking details.</span></div> on my website to keep everyone visiting my site safe. You will recieve a login cookie when you log into my administrator page. This login cookie is meant to add additional security throughout my backend.</span>
    <span>If you attempt to visit my login page, your <div class="tooltip">IP<span class="tooltiptext">IP stands for Internet Protocol and is a uniquely assigned identifier for a certain device on a network. An IP address can contain an approximate location, like a city or county.</span></div> may be logged and I may be able to see the IP. I need this ability to keep my website safe and secure from hackers and malicious users.</span>
    <span>Your IP is logged when you visit my website and also logged when you contact me over my contact form. This allows me to see who is trying to abuse my contact form or trying to abuse my website. I can block certain IP's from visiting my website if they are abusing some feature of my site. If you don't want me to see your real IP, I would recommend using a <div class="tooltip">VPN<span class="tooltiptext">A Virtual Private Network hides the real IP address of a user and masks online activity by encrypting it and routing it through a seperate server.</span></div>. My site is completely compatible with any & all VPNs and I strongly encourage that you use one if available.</span>
    <span>I purposely keep my site simple and secure, to protect users visiting my site from being tracked or hacked. This means that on my site, you shouldn't be tracked. However, on my backend page, you will be tracked if you attempt to log in.</span>
    <span>Additionally, this means that I don't collect any data or sell any data. The only data that I can see is how many visits my website gets and where the visit is from, and I am the only one with access to that information. Data collected is anonymous, meaning it isn't tied to your device. I use this information for recording and administrative purposes. I am currently not aware of anything on my website that is taking data or tracks users on my site. I limit the amount of 3rd parties who have some level of access to my website for additional security for visitors.</span>
    <span>I have multiple systems in place to make sure all visitors are safe while viewing my website. I don't embed any 3rd party websites on my site and I try to serve all data from either my server or Cloudflare's CDN. I use Cloudflare on my website as it makes sure that anyone across the world will still be able to access the website quickly and for the protection of this website. I do not send any website visitor data to Cloudflare. As far as I know, Cloudflare does not collect any data. <a href="https://www.cloudflare.com/privacypolicy/">Cloudflare's privacy policy is located here.</a></span>
    <span>Additionally, this site uses <div class="tooltip">Cloudflare Turnstile<span class="tooltiptext">Cloudflare Turnstile is a free, privacy-focused CAPTCHA replacement provided by Cloudflare that aims to increase user experience while keeping sites secure from bad actors.</span></div> for authentication for my forms. This is to increase my site's security, though it can affect your privacy. You can read <a href="https://www.cloudflare.com/website-terms">Cloudflare's Website Terms</a> if you would like to learn more.</span>
    <span>Please note that I may provide links to outside websites, and I cannot stop those websites from tracking you. These 3rd-party websites may have trackers or cookies and it is not my responsibility to make sure they follow the legal protection acts like GDPR or <div class="tooltip">CalOPPA<span class="tooltiptext">The California Online Privacy Protection Act is a law that requires website owners to publish a privacy policy (like this one) to inform users about how data is collected and used.</span></div>. Additionally, I am not responsible for any content on websites not owned or operated by myself.</span>
    <span>To comply with all of the legal stuff, I must disclose this following information. If you use a <div class="tooltip">DNT<span class="tooltiptext">A Do Not Track request is a deprecated header sent by a browser that asks the requested website to not track a user.</span></div> request it won't do anything, since I dont track anyone by default. If you so choose, you can contact me through my <a href="about-me">Contact section in my About page</a> and ask for any of the personal information that I have collected about you (I dont collect any so the response will most likely be along the lines, "I don't have any data about you.") Also, It is not possible to "opt out" of any data collection since none is collected. Finally, I can not be held liable for any damages / security problems / or anything that may affect you by using my website. In order to comply with <div class="tooltip">COPPA<span class="tooltiptext">The Children's Online Privacy Protection Act places regulations on how data of users under 13 years of age can be collected and is enforced by the FTC.</span></div>, I do not collect any data of users under 13 years of age.</span>
    <span>In order to keep the website fast, data is cached when you visit this website. This cache for most of my website files last for 1800 or 18000 seconds until it expires. Some files that are cached are CSS files, JavaScript files, and images. HTML files aren't usually cached.</span>
    <span>My website is secure, but there is always a chance of a website getting hacked. If this happens, please report to me and I will fix it ASAP! I take many precautions to make sure this site is more difficult to be hacked. I am also using an <div class="tooltip">SSL certificate<span class="tooltiptext">An SSL/TLS certificate allows a website to become more secure by encrypting between the server and end user.</span></div>, which you can see because of the lock icon. This is to further improve the security of the website and to protect your data.</span>
    
    <p>I am always looking out for everyone's safety on my website and take it very, very seriously. If you have any questions or concerns, you may contact me through my [contact form.](about-me#contact) Please browse safely and take care of your privacy online!</p>
    
    <p>My privacy policy was last updated on May 26th, 2023 and updates to this privacy policy could happen without any notice.</p>
    
</div>
<div class="card" id="TLDR">
    
    <h2>TL;DR</h2>
    <p><bold>I don't collect / sell any user data** except for anonymous data regarding your IP. I use Cloudflare on my website, so the [Cloudflare privacy policy](https://www.cloudflare.com/privacypolicy/) applies here. No cookies are created / stored, unless you visit my administration panel or login to my website. When you visit my site your browser automatically downloads a cached version of the page and all assets so it loads quicker for you and uses less bandwidth for me. Please note that your IP is logged when you visit my website or login. Your IP is also logged when you use the contact form. This is to help protect my website against attackers. Browse safely online and protect your important data!</bold></p>
    
</div>